using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraController : MonoBehaviour
{
    public float rotateSpeed = 0.1f;
    [SerializeField] GameObject targetObject;
    Vector3 targetPosition;

    private float angleH;
    private float angleV;

    [SerializeField] float angleUp;
    [SerializeField] float angleDown;
    [SerializeField] float angleRight;
    [SerializeField] float angleLeft;

    // Start is called before the first frame update
    void Start()
    {
        targetPosition = targetObject.transform.position;
    }

    // Update is called once per frame
    void Update()
    {
        Move();
    }

    public void Move()
    {
        //ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Éï¿½ï¿½í‚¹ï¿½ÄƒJï¿½ï¿½ï¿½ï¿½ï¿½ÌˆÚ“ï¿½
        //transform.position += targetObject.transform.position - targetPosition;
        //targetPosition = targetObject.transform.position;

        //ï¿½}ï¿½Eï¿½Xï¿½ÌˆÚ“ï¿½
        float mouseInputX = Input.GetAxis("Mouse X");
        float mouseInputY = Input.GetAxis("Mouse Y");

        //ï¿½}ï¿½Eï¿½Xï¿½Ú“ï¿½ï¿½Ê‚É‚ï¿½ï¿½ï¿½]ï¿½pï¿½x
        float rotateH = mouseInputX * rotateSpeed;
        float rotateV = mouseInputY * rotateSpeed;

        //Xboxï¿½ÌˆÚ“ï¿½
        //float stickInputX = Input.GetAxis("RsitckHorizontal");
        //float stickInputY = Input.GetAxis("RsitckVerticl");

        //Xboxï¿½Ú“ï¿½ï¿½Ê‚É‚ï¿½ï¿½ï¿½]ï¿½pï¿½x
        //float rotateH = -stickInputX * rotateSpeed;
        //float rotateV = -stickInputY * rotateSpeed*0.5f;

        //ï¿½pï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ß‚ï¿½
        angleH += rotateH;
        angleV += rotateV;

        //ï¿½Ú“ï¿½ï¿½pï¿½xï¿½ï¿½ï¿½ï¿½
        float angleLimitH = Mathf.Clamp(angleH, angleLeft, angleRight);
        float angleLimitV = Mathf.Clamp(angleV, angleDown, angleUp);

        //ï¿½ï¿½ï¿½ï¿½ï¿½ÍˆÍ‚ğ’´‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ß‚ï¿½
        float overRangeH = angleH - angleLimitH;
        float overRangeV = angleV - angleLimitV;

        //ï¿½ï¿½]ï¿½Ê‚ğ’²ï¿½
        //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÌŠpï¿½xï¿½ï¿½ï¿½ï¿½
        rotateH -= overRangeH;
        rotateV -= overRangeV;
        angleH = angleLimitH;
        angleV = angleLimitV;

        transform.RotateAround(targetPosition, Vector3.up, rotateH); //Yï¿½ï¿½ï¿½ï¿½ï¿½Sï¿½É‰ï¿½]
        transform.RotateAround(targetPosition, transform.right, rotateV); //Xï¿½ï¿½ï¿½ï¿½ï¿½Sï¿½É‰ï¿½]
    }
}
